Missing loaders in for release (#34)
I get errors if I do a npm run release
If I understand correctly, there are missing loaders.

ModuleParseError: Module parse failed: Unexpected character '�' (1:0)

Thanks for checking!